'use strict';

(() => {
  const Q=window.RailwayQuestions, PARTS=window.RailwayParts, E=window.RailwayEngine;
  const app=document.querySelector('#app'), KEY='wise-frog-if-when-v5', PREVIOUS_KEY='wise-frog-if-when-v4', OLD_KEY='wise-frog-if-when-v3';
  let state={screen:'start',hero:'frog',index:0,lives:3,streak:0,eggs:0,seconds:0,records:[],answer:'',feedback:null,audioOn:true};
  let saved=null,storageOK=true,tickAt=Date.now(),audioContext=null,audioTimer=null;
  const eggsFor=records=>E.eggCount(records);
  try{
    const current=localStorage.getItem(KEY);
    if(current){const data=JSON.parse(current);if(data?.version===5&&data.state?.records?.length===15&&['part','game','finish'].includes(data.state.screen))saved=data.state;}
    else {
      const previous=localStorage.getItem(PREVIOUS_KEY),data=JSON.parse(previous||localStorage.getItem(OLD_KEY));
      if(data?.state?.records?.length===15&&['part','game','finish'].includes(data.state.screen)){
        saved=data.state;
        if(previous&&data.version===4&&saved.index>=13){saved.records=[...saved.records.slice(0,13),...Q.slice(13).map(E.createRecord)];saved.index=13;saved.screen='game';saved.answer='';saved.feedback=null;saved.streak=0;}
        else if(!previous&&data.version===3){saved.records=[...saved.records.slice(0,10),...Q.slice(10).map(E.createRecord)];if(saved.index>=10){saved.index=10;saved.screen='part';saved.answer='';saved.feedback=null;saved.streak=0;saved.revisedQuestions=true;}}
      }
    }
    if(saved){saved.eggs=eggsFor(saved.records);state.hero=saved.hero||'frog';}
  }catch{storageOK=false;}
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const q=()=>Q[state.index],record=()=>state.records[state.index],part=()=>PARTS[q()?.part-1||0];
  const clock=()=>`${String(Math.floor(state.seconds/60)).padStart(2,'0')}:${String(state.seconds%60).padStart(2,'0')}`;
  function save(){try{localStorage.setItem(KEY,JSON.stringify({version:5,state}));}catch{storageOK=false;}}

  function scheduleArcadeLoop(){
    if(!audioContext||!state.audioOn)return;
    const melody=[523,659,784,659,587,698,880,698,523,659,784,1047,880,784,659,587];
    const start=audioContext.currentTime+.05;
    melody.forEach((frequency,i)=>{
      const osc=audioContext.createOscillator(),gain=audioContext.createGain();
      osc.type=i%4===3?'square':'triangle';osc.frequency.value=frequency;
      gain.gain.setValueAtTime(.0001,start+i*.14);gain.gain.exponentialRampToValueAtTime(.07,start+i*.14+.012);gain.gain.exponentialRampToValueAtTime(.0001,start+i*.14+.115);
      osc.connect(gain).connect(audioContext.destination);osc.start(start+i*.14);osc.stop(start+i*.14+.13);
    });
    [131,147,165,147].forEach((frequency,i)=>{
      const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='square';osc.frequency.value=frequency;
      gain.gain.setValueAtTime(.03,start+i*.56);gain.gain.exponentialRampToValueAtTime(.0001,start+i*.56+.34);osc.connect(gain).connect(audioContext.destination);osc.start(start+i*.56);osc.stop(start+i*.56+.36);
    });
  }
  async function startAudio(){
    const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;
    if(!audioContext)audioContext=new Audio();
    await audioContext.resume();scheduleArcadeLoop();clearInterval(audioTimer);audioTimer=setInterval(scheduleArcadeLoop,2240);
  }
  function stopAudio(){clearInterval(audioTimer);audioTimer=null;if(audioContext)audioContext.suspend();}
  function playSfx(kind){
    if(!audioContext||!state.audioOn||audioContext.state!=='running')return;
    const now=audioContext.currentTime,notes=kind==='wrong'?[220,185]:kind==='egg'?[523,659,784,1047,1319,1568]:[659,784,1047];
    notes.forEach((frequency,i)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain(),at=now+i*(kind==='egg'?.12:.09);osc.type=kind==='egg'?'triangle':'square';osc.frequency.value=frequency;gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(kind==='egg'?.2:.16,at+.01);gain.gain.exponentialRampToValueAtTime(.0001,at+(kind==='egg'?.2:.13));osc.connect(gain).connect(audioContext.destination);osc.start(at);osc.stop(at+(kind==='egg'?.22:.15));});
    if(kind==='wrong')return;
    const cheerAt=now+(kind==='egg'?.1:.08),duration=kind==='egg'?1.15:.48;
    [0,.13,.27].forEach((offset,i)=>{const voice=audioContext.createOscillator(),gain=audioContext.createGain(),at=cheerAt+offset;voice.type='sawtooth';voice.frequency.setValueAtTime(370+i*45,at);voice.frequency.exponentialRampToValueAtTime(620+i*65,at+.2);gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(kind==='egg'?.042:.025,at+.06);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);voice.connect(gain).connect(audioContext.destination);voice.start(at);voice.stop(at+duration+.02);});
    if(kind==='egg'){const length=Math.floor(audioContext.sampleRate*.8),buffer=audioContext.createBuffer(1,length,audioContext.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<length;i++)samples[i]=(Math.random()*2-1)*.24;const noise=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),gain=audioContext.createGain();noise.buffer=buffer;filter.type='lowpass';filter.frequency.value=1600;gain.gain.setValueAtTime(.0001,cheerAt);gain.gain.exponentialRampToValueAtTime(.08,cheerAt+.12);gain.gain.exponentialRampToValueAtTime(.0001,cheerAt+.8);noise.connect(filter).connect(gain).connect(audioContext.destination);noise.start(cheerAt);noise.stop(cheerAt+.8);}
  }

  function hero(kind,extra=''){
    if(kind==='frog')return `<svg class="hero ${extra}" viewBox="0 0 150 150" aria-hidden="true"><ellipse cx="75" cy="139" rx="43" ry="7" fill="#1b2945" opacity=".18"/><g stroke="#28462e" stroke-width="3"><ellipse cx="75" cy="108" rx="33" ry="30" fill="#76bd54"/><circle cx="49" cy="48" r="22" fill="#84cf61"/><circle cx="101" cy="48" r="22" fill="#84cf61"/><ellipse cx="75" cy="75" rx="48" ry="34" fill="#84cf61"/></g><g fill="#fff"><circle cx="49" cy="47" r="14"/><circle cx="101" cy="47" r="14"/></g><g fill="#263b2c"><circle cx="52" cy="48" r="6"/><circle cx="98" cy="48" r="6"/></g><path d="M52 78q23 20 46 0" fill="none" stroke="#28462e" stroke-width="4" stroke-linecap="round"/><path d="M50 101l25 12 25-12-9 23-16-10-17 10z" fill="#ffcb42" stroke="#9b6b24" stroke-width="2"/><path d="M45 119l-26 17h43m43-17 27 17H88" fill="#76bd54" stroke="#28462e" stroke-width="3"/></svg>`;
    if(kind==='zak')return `<svg class="hero ${extra}" viewBox="0 0 150 150" aria-hidden="true"><ellipse cx="75" cy="140" rx="39" ry="7" fill="#1b2945" opacity=".16"/><path d="M51 91L37 131h76L98 91z" fill="#4d94d2" stroke="#275d90" stroke-width="3"/><path d="M49 98l-21 20m73-20 21 20" stroke="#efbd91" stroke-width="10" stroke-linecap="round"/><ellipse cx="75" cy="62" rx="32" ry="34" fill="#f2c49a" stroke="#714a3a" stroke-width="2"/><path d="M43 56q-2-32 23-38 28-7 43 17l-5 18-9-16-9 11-8-14-12 13-8-11-15 20z" fill="#3b2b28" stroke="#2b211f" stroke-width="3" stroke-linejoin="round"/><g fill="#fff" stroke="#34445c" stroke-width="3"><circle cx="61" cy="64" r="11"/><circle cx="89" cy="64" r="11"/></g><path d="M72 64h6" stroke="#34445c" stroke-width="3"/><path d="M50 61l-8-3m58 3 8-3" stroke="#34445c" stroke-width="3" stroke-linecap="round"/><g fill="#29333f"><circle cx="63" cy="65" r="4"/><circle cx="87" cy="65" r="4"/></g><path d="M67 80q8 7 16 0" fill="none" stroke="#a35d55" stroke-width="2" stroke-linecap="round"/><path d="M55 94l20 13 20-13" fill="#fff1ce"/><path d="M55 25l-2-17 13 8 9-14 10 14 13-8-3 18" fill="#ffd04e" stroke="#a87927" stroke-width="2"/><circle cx="75" cy="110" r="4" fill="#ffd04e"/></svg>`;
    return `<svg class="hero ${extra}" viewBox="0 0 150 150" aria-hidden="true"><ellipse cx="75" cy="140" rx="39" ry="7" fill="#1b2945" opacity=".16"/><path d="M39 77q-9-58 36-60 45 2 37 60l-7 35H46z" fill="#6d4038" stroke="#3f302c" stroke-width="3"/><path d="M52 91L36 130h78L98 91z" fill="#f287ad" stroke="#a74469" stroke-width="3"/><path d="M48 97l-21 21m75-21 21 21" stroke="#efbd91" stroke-width="10" stroke-linecap="round"/><ellipse cx="75" cy="61" rx="33" ry="35" fill="#f2c49a" stroke="#714a3a" stroke-width="2"/><path d="M41 54q1-35 35-32 31-2 35 33-24-2-36-18-12 15-34 17" fill="#6d4038"/><g fill="#fff" stroke="#5b3b36" stroke-width="2"><ellipse cx="61" cy="63" rx="9" ry="11"/><ellipse cx="90" cy="63" rx="9" ry="11"/></g><g fill="#29333f"><circle cx="63" cy="65" r="5"/><circle cx="88" cy="65" r="5"/></g><g stroke="#47332f" stroke-width="2" stroke-linecap="round"><path d="M52 54l-5-5m8 2-2-7m45 10 5-5m-8 2 2-7"/></g><path d="M67 79q8 7 16 0" fill="none" stroke="#a35d55" stroke-width="2" stroke-linecap="round"/><path d="M53 27l-3-19 15 9 10-15 11 15 15-9-4 20z" fill="#ffd04e" stroke="#a87927" stroke-width="2"/><circle cx="75" cy="20" r="4" fill="#e2576f"/><path d="M52 111q23-10 46 0" fill="none" stroke="#ffd4df" stroke-width="5"/></svg>`;
  }

  function scenery(){
    const p=part(),local=(state.index%5+(record()?.completed?1:0))/5,position=7+local*82;
    const backgrounds={
      garden:`<rect width="1200" height="270" fill="#82d5e8"/><circle cx="1030" cy="48" r="35" fill="#ffe264"/><path d="M0 187Q170 70 350 177T730 173T1200 155V270H0" fill="#73bd63"/><path d="M0 218Q210 132 420 217T810 205T1200 190V270H0" fill="#4f9f59"/><g transform="translate(70 62)"><path d="M0 132V55h39v77m9 0V20h94v112m10 0V55h39v77" fill="#fff0c9" stroke="#865c4b" stroke-width="3"/><path d="M-8 55L20 24l28 31m-4-35 52-52 51 52m-4 35 28-31 28 31" fill="#ed7568" stroke="#93473f" stroke-width="3"/></g><g fill="#fff3a5"><circle cx="410" cy="218" r="6"/><circle cx="442" cy="212" r="6"/><circle cx="975" cy="205" r="6"/></g>`,
      pond:`<rect width="1200" height="270" fill="#6fc5dd"/><circle cx="150" cy="52" r="30" fill="#fff1a0"/><path d="M0 163Q210 95 405 166T800 159T1200 145V270H0" fill="#5fa96a"/><ellipse cx="615" cy="221" rx="390" ry="79" fill="#4fa7b7"/><path d="M180 179Q600 72 1020 179" fill="none" stroke="#e8cf97" stroke-width="35"/><path d="M180 178Q600 72 1020 178" fill="none" stroke="#9d7146" stroke-width="5" stroke-dasharray="28 18"/><g fill="#7ebc5e"><ellipse cx="420" cy="225" rx="35" ry="10"/><ellipse cx="795" cy="218" rx="40" ry="11"/><ellipse cx="950" cy="237" rx="28" ry="8"/></g><g fill="#ffd06b"><circle cx="425" cy="213" r="7"/><circle cx="790" cy="205" r="7"/></g>`,
      mountain:`<rect width="1200" height="270" fill="#343765"/><circle cx="1020" cy="50" r="32" fill="#fff1bd"/><g fill="#fff"><circle cx="116" cy="54" r="3"/><circle cx="340" cy="31" r="3"/><circle cx="720" cy="58" r="3"/><circle cx="900" cy="27" r="3"/></g><path d="M0 214L180 75l125 104L480 44l188 159L830 80l165 125 205-128V270H0" fill="#5f7292"/><path d="M0 239L202 129l135 104L515 100l161 132 191-95 142 87 191-87V270H0" fill="#3e596f"/><path d="M0 224Q250 167 460 209T840 184T1200 198" fill="none" stroke="#d6bd85" stroke-width="36"/><path d="M0 224Q250 167 460 209T840 184T1200 198" fill="none" stroke="#7c5944" stroke-width="5" stroke-dasharray="28 18"/>`
    };
    const y={garden:[175,163,177,160,174],pond:[176,145,160,136,155],mountain:[184,161,142,160,135]}[p.theme][state.index%5];
    return `<section class="track-stage theme-${p.theme}" aria-label="${esc(p.name)}: your character is ${Math.round((state.index+(record()?.completed?1:0))/15*100)} percent of the way to the final finish line"><svg viewBox="0 0 1200 270" preserveAspectRatio="xMidYMid slice" aria-hidden="true">${backgrounds[p.theme]}</svg><div class="track-title"><b>PART ${p.number}</b><span>${p.name}</span></div><div class="train" style="left:${position}%;top:${y/270*100}%">${hero(state.hero,'train-hero')}<div class="engine"><span>★</span><i></i><i></i></div></div><div class="finish-sign">PART ${p.number}<br>FINISH ⚑</div><div class="overall-progress"><span style="width:${(state.index+(record()?.completed?1:0))/15*100}%"></span></div></section>`;
  }

  function header(){return `<header class="topbar"><a class="brand" href="./index.html"><img src="icon.svg" alt="" width="38"><span>WISE FROG<span>IF & WHEN RAILWAY</span></span></a><div><span class="timer">◷ <span id="timer">${clock()}</span></span><button class="quiet small" data-action="sound" aria-pressed="${state.audioOn}">${state.audioOn?'♫ Arcade sound on':'♫ Arcade sound off'}</button><button class="quiet small" data-action="teacher">Teacher notes</button></div></header>`;}
  function startScreen(){
    const choices=[['frog','Wise Frog','A clever pond guide'],['princess','Princess','Bright eyes, brave heart'],['zak','Prince Zak','Ready for adventure']];
    return `<div class="start-layout"><section class="welcome"><p class="eyebrow">PRIMARY 3 · GRAMMAR LS8.5</p><h1>Race the rails<br>with <em>if & when!</em></h1><p class="lead">Type complete sentences, repair three remarkable tracks and reach the final flag.</p><div class="walt"><b>WE ARE LEARNING TO</b><p>Form sentences using <strong>if</strong> and use <strong>when</strong> to show the correct sequence of events.</p></div><div class="egg-challenge"><b>🥚 SECRET EGG CHALLENGE</b><p>Find one egg after every 3 completed questions, even if you needed a retry or hint. Collect all 5 eggs to earn ClassDojo points from your teacher!</p></div></section><section class="boarding paper"><p class="eyebrow">CHOOSE YOUR DRIVER</p><div class="hero-options">${choices.map(([id,name,note])=>`<button class="hero-choice ${state.hero===id?'selected':''}" data-hero="${id}" aria-pressed="${state.hero===id}">${hero(id)}<strong>${name}</strong><small>${note}</small><span>${state.hero===id?'✓':'○'}</span></button>`).join('')}</div><div class="journey-preview">${PARTS.map(p=>`<div><b>${p.number}</b><span>${p.name}<small>${p.range}</small></span></div>`).join('')}</div><button class="primary wide" data-action="${saved?'resume':'start'}">${saved?'CONTINUE MY JOURNEY':'START THE ENGINE + SOUND'} <span>→</span></button>${saved?'<button class="quiet wide resume" data-action="start">Start a new journey</button>':''}<p class="boarding-note">15 typed answers · arcade sound starts with the engine · 5 secret eggs</p></section></div>`;
  }
  function partIntro(){const p=part();return `<section class="part-intro paper"><p class="eyebrow">NEW TRACK REVEALED</p><span class="part-number">${p.number}</span><h1>${p.name}</h1><p>${p.range} · ${p.focus}</p>${state.revisedQuestions?'<p>Questions 11–15 are new. Your first ten answers and eggs have been kept.</p>':''}<div class="part-map ${p.theme}"><i></i><i></i><i></i><i></i><i></i><span>⚑</span></div><button class="primary" data-action="enter">ENTER PART ${p.number} <span>→</span></button></section>`;}
  function answerPrompt(item){
    if(item.type==='combine')return `<h1>Combine the sentences using <em>${item.connector}</em>.</h1><div class="source-sentences"><p><span>A</span>${esc(item.a)}</p><p><span>B</span>${esc(item.b)}</p></div>`;
    return `<h1>Complete the sentence.</h1><div class="completion-card"><p>${esc(item.stem)}</p><span>Use these words: <b>${esc(item.prompt)}</b></span></div>`;
  }
  function gameScreen(){const item=q(),r=record(),completed=state.records.filter(x=>x.completed).length;return `<div class="play-layout"><aside class="buddy paper">${hero(state.hero)}<p class="eyebrow">YOUR DRIVER</p><h2>${state.hero==='frog'?'Wise Frog':state.hero==='princess'?'Princess':'Prince Zak'}</h2><div class="score"><span>Lives <b>♥ ${state.lives}</b></span><span>Streak <b>${'★'.repeat(state.streak)}${'☆'.repeat(3-state.streak)}</b></span></div><div class="egg-meter"><b>SECRET EGGS ${state.eggs}/5</b><div class="egg-row" aria-label="${state.eggs} of 5 secret eggs collected">${Array.from({length:5},(_,i)=>`<span class="${i<state.eggs?'found':''}">🥚</span>`).join('')}</div></div><p>${completed===15?'All five eggs found!':`Next egg after ${Math.min(15,(state.eggs+1)*3)} completed questions. ${completed}/15 done.`}</p><button class="quiet wide" data-action="pause">Save & take a break</button></aside><section class="question paper"><div class="question-top"><span>QUESTION ${String(state.index+1).padStart(2,'0')} / 15</span><b>${esc(item.skill)}</b></div><div class="mini-progress"><span style="width:${(state.index+(r.completed?1:0))/15*100}%"></span></div>${answerPrompt(item)}<label for="answer">Type the complete sentence</label><textarea id="answer" rows="3" spellcheck="false" autocapitalize="sentences" placeholder="Type your complete sentence here…" ${r.completed?'disabled':''}>${esc(state.answer)}</textarea><div class="input-note"><span>Spelling, grammar, capital letters and punctuation are checked.</span><button class="text-button" data-action="clear" ${r.completed?'disabled':''}>Clear</button></div>${r.hint&&!r.completed?`<div class="hint"><b>THINK ABOUT THE ORDER</b><p>${esc(item.hint)}</p></div>`:''}${state.feedback?`<div id="feedback" class="feedback ${state.feedback.correct?'correct':'wrong'}" role="status" tabindex="-1"><strong>${state.feedback.title}</strong><p>${esc(state.feedback.message)}</p>${r.model?`<p class="model"><b>Correct model:</b> ${esc(state.feedback.model)}</p>`:''}</div>`:''}<div class="actions">${r.completed?`<button class="primary" data-action="next">${state.index===14?'CROSS THE FINISH LINE':state.index===4||state.index===9?'REVEAL THE NEXT TRACK':'NEXT QUESTION'} <span>→</span></button>`:`<button class="primary" data-action="check" ${state.answer.trim()?'':'disabled'}>CHECK MY SENTENCE <span>✓</span></button><button class="quiet" data-action="hint" ${r.hint?'disabled':''}>${r.hint?'Hint opened':'✦ Sequence hint'}</button>${r.attempts.length?'<button class="quiet" data-action="model">Show a correct model</button>':''}`}</div><p class="assessment-note">Your first answer is kept separately from retries and support.</p></section></div>`;}
  function statusLabel(r){if(r.attempts[0]?.correct&&r.attempts[0]?.independent)return 'Independent';if(r.completed)return r.hint||r.model?'Correct after support':'Correct after retry';return 'Incomplete';}
  function finishScreen(){const stats=E.stats(state.records),skills=[...new Set(Q.map(x=>x.skill))],eggMessage=state.eggs===5?'Maximum eggs collected! Show this screen to your teacher to receive ClassDojo points.':`You found ${state.eggs} of 5 secret eggs. Try again to collect the maximum!`;return `<section class="results paper">${hero(state.hero,'finish-hero')}<p class="eyebrow">ALL THREE TRACKS COMPLETE</p><h1>HOORAY,<br><em>YOU DID IT!</em></h1><p>You reached the final flag by building 15 complete sentences.</p><div class="egg-finish"><b>🥚 ${state.eggs}/5 SECRET EGGS</b><p>${eggMessage}</p></div><div class="result-stats"><div><b>${stats.independent}<small>/15</small></b><span>Independent first answers</span></div><div><b>${state.eggs}<small>/5</small></b><span>Secret eggs</span></div><div><b>${clock()}</b><span>Thinking time</span></div><div><b>${state.lives} ♥</b><span>Lives left</span></div></div><div class="teacher-results"><h2>Learning results</h2><p>Independent means correct on the first try before a hint or model answer.</p>${skills.map(skill=>{const rows=state.records.filter(r=>r.skill===skill);return `<div class="skill-row"><b>${esc(skill)}</b><span>${E.stats(rows).independent}/${rows.length} independent</span></div>`;}).join('')}<details><summary>Review first answers and corrections</summary>${state.records.map((r,i)=>{const item=Q[i],first=r.attempts[0];return `<details class="answer-review"><summary>${item.id} · ${statusLabel(r)}</summary><p><b>First answer:</b> ${esc(first?.answer||'No answer')}</p><p><b>Correct model:</b> ${esc(item.answers[0])}</p><p><b>Teaching point:</b> ${esc(item.explanation)}</p></details>`;}).join('')}</details><p class="small-note">${stats.hints} hints · ${stats.retries} retried questions · ${stats.models} model answers shown. Results stay on this device.</p></div><div class="finish-actions"><button class="primary" data-action="restart">PLAY AGAIN <span>→</span></button><button class="quiet" data-action="export">Download results</button><button class="quiet" data-action="print">Print</button></div><p id="export-status" role="status"></p></section>`;}
  function teacherDialog(){return `<dialog id="teacher"><div><h2>Teacher notes</h2><button class="quiet" data-action="close-teacher">Close ×</button></div><p><b>One game, 15 typed answers:</b> Q1–10 combine complete ideas using <i>if</i> or <i>when</i>. Q11–15 now use original railway-story prompts and the helping words shown on screen. Q6 also requires the pronoun <i>it</i>.</p><p>For Q11–15, the checker accepts common grammatical alternatives including “has to”, “should”, and contractions. Q14 allows a command with an understood “you”; Q15 asks for a passive phrase with “informed”. An opening if-clause needs a comma. A final if-clause does not.</p><p>Hints identify the condition or earlier event. First answers remain separate from retries, hints and model answers. If a pupil gives an unusual but valid construction outside the prompted pattern, review it together.</p><p><b>Secret eggs:</b> one egg appears after 3, 6, 9, 12 and 15 correctly completed questions. Retries and hints do not prevent an egg. The independent first-try streak still awards bonus lives.</p><button class="primary" data-action="close-teacher">READY</button></dialog>`;}
  function render(focus){app.innerHTML=header()+(state.screen!=='start'?scenery():'')+(state.screen==='start'?startScreen():state.screen==='part'?partIntro():state.screen==='game'?gameScreen():finishScreen())+teacherDialog()+`<footer><span>MADE FOR LITTLE THINKERS</span><span>Prince Zak · Primary 3 English</span></footer>`;if(!storageOK)app.insertAdjacentHTML('beforeend','<p class="storage-warning">Progress cannot be saved in this browser.</p>');if(focus){const el=document.querySelector(focus);el?.focus({preventScroll:true});el?.scrollIntoView({block:'nearest'});}}
  function celebrate(egg=false){const box=document.querySelector('#celebration');box.innerHTML=Array.from({length:28},(_,i)=>`<i style="--x:${i*37%100}%;--d:${i%7*.05}s;--c:${['#ffcf3f','#49b6d6','#f276a7','#70b950'][i%4]}"></i>`).join('')+(egg?'<div class="egg-reveal"><span>🥚</span><b>SECRET EGG FOUND!</b><small>Keep going for ClassDojo points!</small></div>':'');setTimeout(()=>box.innerHTML='',egg?2400:1600);}
  function newGame(){state={screen:'part',hero:state.hero,index:0,lives:3,streak:0,eggs:0,seconds:0,records:Q.map(E.createRecord),answer:'',feedback:null,audioOn:true};saved=null;tickAt=Date.now();startAudio();save();render('.part-intro h1');}
  function check(){const result=E.submit(state,q(),record(),state.answer);if(!result)return;const earned=eggsFor(state.records),eggFound=result.correct&&earned>state.eggs;state.eggs=earned;state.feedback={...result,title:result.correct?(eggFound?'Correct! Secret egg found!':'Correct! The train moves forward!'):(result.kind==='punctuation'?'Fix the punctuation or capital letter.':result.kind==='meaning'?'The meaning has changed.':'Check your spelling and grammar.')};playSfx(result.correct?(eggFound?'egg':'correct'):'wrong');if(result.correct)celebrate(eggFound);save();render('#feedback');}
  function exportResults(){const rows=[['Question','Skill','Attempt','Answer','Correct','Error type','Independent','Hint used','Model shown']];state.records.forEach(r=>(r.attempts.length?r.attempts:[{}]).forEach((a,i)=>rows.push([r.id,r.skill,i+1,a.answer||'',a.correct??'',a.kind||'',a.independent??'',r.hint,r.model])));const csv='\uFEFF'+rows.map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`if-when-railway-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);document.querySelector('#export-status').textContent='Download requested. On iPad, check Safari Downloads.';}
  app.addEventListener('input',e=>{if(e.target.id==='answer'){state.answer=e.target.value;document.querySelector('[data-action="check"]').disabled=!state.answer.trim();save();}});
  app.addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b||b.disabled)return;
    if(b.dataset.hero){state.hero=b.dataset.hero;render();document.querySelector(`[data-hero="${state.hero}"]`)?.focus();return;}
    switch(b.dataset.action){
      case'start':newGame();break;
      case'resume':state={...saved,hero:state.hero};saved=null;if(state.audioOn)startAudio();save();render(state.screen==='game'?'#answer':state.screen==='finish'?'.results h1':'.part-intro h1');break;
      case'enter':state.screen='game';state.revisedQuestions=false;save();render('#answer');break;
      case'check':check();break;
      case'hint':E.support(state,record(),'hint');save();render('.hint');break;
      case'model':E.support(state,record(),'model');state.feedback={correct:false,title:'Study this model, then type it yourself.',message:q().explanation,model:q().answers[0]};save();render('#feedback');break;
      case'clear':state.answer='';state.feedback=null;save();render('#answer');break;
      case'next':if(!record().completed)return;if(state.index===14){state.screen='finish';stopAudio();celebrate();}else{state.index++;state.answer='';state.feedback=null;state.screen=state.index===5||state.index===10?'part':'game';}save();render(state.screen==='game'?'#answer':state.screen==='part'?'.part-intro h1':'.results h1');break;
      case'pause':save();saved=JSON.parse(JSON.stringify(state));state.screen='start';stopAudio();render('h1');break;
      case'restart':state.screen='start';state.index=0;state.answer='';state.feedback=null;state.eggs=0;saved=null;stopAudio();save();render('h1');break;
      case'sound':state.audioOn=!state.audioOn;state.audioOn?startAudio():stopAudio();save();render();document.querySelector('[data-action="sound"]')?.focus();break;
      case'teacher':document.querySelector('#teacher').showModal();break;
      case'close-teacher':document.querySelector('#teacher').close();break;
      case'export':exportResults();break;
      case'print':window.print();break;
    }
  });
  setInterval(()=>{const now=Date.now();if(state.screen==='game'&&!document.hidden&&!document.querySelector('#teacher')?.open){state.seconds+=Math.min(2,Math.round((now-tickAt)/1000));document.querySelector('#timer').textContent=clock();if(state.seconds%10===0)save();}tickAt=now;},1000);
  document.addEventListener('visibilitychange',()=>{tickAt=Date.now();if(document.hidden)stopAudio();else if(state.audioOn&&state.screen!=='finish')startAudio();});
  window.addEventListener('pagehide',()=>{if(state.screen!=='start')save();});render();
})();
