/* Original practice items aligned to P3 Unit 8. No reader pages or illustrations are bundled. */
'use strict';
const connectorRows = [
 ['You help the frog','he will show you the track','if','Helping the frog is the condition for his offer to show you the track.'],
 ['It rains','the princess will wait in the station','if','Rain is the condition. The princess will wait if that condition happens.'],
 ['You find the wheel','we can repair the carriage','if','Finding the wheel is the condition that makes the repair possible.'],
 ['The signal turns green','the train can leave','if','The green signal is the condition for the train to leave.'],
 ['The frog was cleaning the pond','the princess was collecting leaves','while','Both actions were happening at the same time.'],
 ['Zak was holding the ladder','the princess was fixing the sign','while','Holding the ladder and fixing the sign were happening together.'],
 ['The passengers were waiting','the frog was checking the wheels','while','The passengers waited during the wheel check.'],
 ['The princess was reading the map','Zak was packing the bags','while','Reading the map and packing the bags were happening at the same time.'],
 ['The water rose','the little boat floated higher','as','As links the rising water with the boat moving higher.'],
 ['The train entered the tunnel','the garden disappeared from view','as','The garden disappeared from view as the train entered the tunnel.'],
 ['The carriage rolled downhill','its wheels spun faster','as','The wheels spun faster as the carriage rolled downhill.'],
 ['The train passed the pond','the frog waved to his friends','as','The frog waved during the journey past the pond.']
];
const connectors = connectorRows.map(([a,b,word,explanation],i)=>({id:`C${String(i+1).padStart(2,'0')}`,type:'connector',skill:word,a,b,word,explanation}));
const inference = [
 {id:'I01',skill:'Motives',prompt:'Why is Zak cautious when the frog asks for a favour?',clue:'Zak remembers frog stories. Some of them did not turn out well.',page:'Reader p. 4',options:['He is unsure what the frog will ask him to do.','He already knows that the frog wants a crown.','He has forgotten where he lost the ball.'],answer:0,evidence:['Zak has a rubber ball.','Zak remembers frog stories that did not all end well.','Zak is in the palace garden.'],proof:1,explanation:'His memories help explain his caution. The story does not say that the frog wants a crown.'},
 {id:'I02',skill:'Character',prompt:'What does the solution suggest about the frog?',clue:'The frog gets Zak to put the hose in the hole. He turns on the water, and the ball rises.',page:'Reader pp. 5–6',options:['He solves problems thoughtfully.','He can make any object float by magic.','He is stronger than the builders.'],answer:0,evidence:['The frog lives near the palace.','The ball belongs to Zak.','The frog uses water to bring the ball up.'],proof:2,explanation:'The water solution supports the idea that the frog thinks carefully. There is no evidence of magic or unusual strength.'},
 {id:'I03',skill:'Feelings',prompt:'How does Zak probably feel when the ball rises?',clue:'Zak sees the ball coming up and enthusiastically praises the frog’s idea.',page:'Reader p. 6',options:['Angry with the frog.','Excited and relieved.','Bored by the rescue.'],answer:1,evidence:['Zak enthusiastically praises the idea as the ball rises.','There is a shed in the garden.','Zak used a stick earlier.'],proof:0,explanation:'His enthusiastic reaction supports excitement and relief at getting his ball back.'},
 {id:'I04',skill:'Character',prompt:'What does Zak’s response at the end suggest?',clue:'The frog has helped Zak. Zak immediately says he will get a bucket and gloves for cleaning the pond.',page:'Reader p. 6',options:['He is planning to hide the ball.','He wants to avoid the frog.','He is grateful and ready to keep his agreement.'],answer:2,evidence:['The ball bounced against the shed.','Zak immediately prepares to clean the pond.','There are builders in the garden.'],proof:1,explanation:'Preparing to clean the pond shows that Zak is ready to do what he agreed to do.'},
 {id:'I05',skill:'Motives',prompt:'Why does the ball’s material matter to the frog?',clue:'The frog checks what the ball is made of before using water to raise it out of the hole.',page:'Reader pp. 3, 5–6',options:['He wants a ball that matches the pond.','His plan depends on the ball floating.','He wants to sell the ball.'],answer:1,evidence:['The frog asks about the material and then uses water to lift the ball.','Zak’s family lives in a palace.','The frog has yellow eyes.'],proof:0,explanation:'The plan uses floating, so the ball’s material matters. The clues do not suggest selling or decorating it.'},
 {id:'I06',skill:'Motives',prompt:'What does the frog seem to want Zak to remember?',clue:'After helping Zak, the frog looks at his dirty pond while speaking about things people overlook.',page:'Reader p. 6',options:['The builders’ new bird house.','The colour of the garden shed.','The agreement to clean the pond.'],answer:2,evidence:['Zak’s ball is hollow.','The frog looks towards the dirty pond after the rescue.','Zak first tries a stick.'],proof:1,explanation:'Looking at the pond connects the frog’s words to the cleaning agreement.'},
 {id:'I07',skill:'Feelings',prompt:'Why is Zak startled when the frog first speaks?',clue:'When the frog offers to help, Zak reacts with shock that a frog is talking to him.',page:'Reader p. 3',options:['A talking frog is unexpected to him.','He has just seen a train.','He knows the frog is angry.'],answer:0,evidence:['Zak has a ball.','There is mud beside the pond.','Zak reacts with shock to the frog speaking.'],proof:2,explanation:'His reaction is to the frog talking. The other answers add ideas that the clue does not support.'},
 {id:'I08',skill:'Text connections',prompt:'Who does the companion story suggest the princess is?',clue:'Zak says his parents met over a gold ball. In The Frog Prince, a princess loses a gold ball and meets the frog who becomes a prince.',page:'Reader pp. 3, 7, 9',options:['Zak’s sister.','Zak’s mother.','Zak’s teacher.'],answer:1,evidence:['Both stories happen outdoors.','Both stories mention a ball.','Zak’s parents and the princess’s story share the gold-ball meeting.'],proof:2,explanation:'The matching detail about how his parents met points to the princess being his mother. A ball alone is not enough evidence.'}
].map(q=>({...q,type:'inference'}));
window.RailwayPacks={connectors,inference};
