'use strict';

/* Original classroom questions aligned to Grammar LS8.5. */
window.RailwayQuestions = [
  {id:'Q01',part:1,type:'combine',connector:'if',skill:'Condition with if',a:'You help the Wise Frog.',b:'He will show you the safest track.',answers:['If you help the Wise Frog, he will show you the safest track.','He will show you the safest track if you help the Wise Frog.'],hint:'Which event must happen first as a condition? Helping the Wise Frog must happen before he will show you the track.',explanation:'Helping the Wise Frog is the condition. The if-clause must contain that condition; reversing the relationship changes the meaning.'},
  {id:'Q02',part:1,type:'combine',connector:'when',skill:'Sequence with when',a:'The station bell rings.',b:'The passengers board the train.',answers:['When the station bell rings, the passengers board the train.','The passengers board the train when the station bell rings.'],hint:'Which event signals that the next action should begin? The bell rings first; boarding follows.',explanation:'The ringing bell is the time signal. “When” belongs with that event, and boarding follows.'},
  {id:'Q03',part:1,type:'combine',connector:'if',skill:'Condition with if',a:'Prince Zak finds the missing wheel.',b:'The train can leave the palace garden.',answers:['If Prince Zak finds the missing wheel, the train can leave the palace garden.','The train can leave the palace garden if Prince Zak finds the missing wheel.'],hint:'Can the train leave before the wheel is found? Decide which event is the condition.',explanation:'Finding the wheel is the condition that makes leaving possible. The if-clause must describe Prince Zak finding it.'},
  {id:'Q04',part:1,type:'combine',connector:'when',skill:'Sequence with when',a:'The signal turns green.',b:'The driver starts the engine.',answers:['When the signal turns green, the driver starts the engine.','The driver starts the engine when the signal turns green.'],hint:'Look for the signal that tells the driver it is time to act. Which event happens first?',explanation:'The green signal comes first and tells the driver when to start.'},
  {id:'Q05',part:1,type:'combine',connector:'if',skill:'Condition with if',a:'The rain becomes heavier.',b:'The friends will wait inside the station.',answers:['If the rain becomes heavier, the friends will wait inside the station.','The friends will wait inside the station if the rain becomes heavier.'],hint:'The friends will wait only under one condition. What must happen to the rain?',explanation:'Heavier rain is the condition for waiting inside. The waiting is the result.'},
  {id:'Q06',part:2,type:'combine',connector:'when',skill:'Sequence with when + pronoun',a:'The water reaches the rubber ball.',b:'The rubber ball begins to float upwards.',answers:['When the water reaches the rubber ball, it begins to float upwards.','The rubber ball begins to float upwards when the water reaches it.'],hint:'The water reaches the rubber ball first. In your combined sentence, replace the repeated words “the rubber ball” with the pronoun “it”.',explanation:'The water reaching the ball triggers the next event. The pronoun “it” replaces the repeated noun phrase “the rubber ball” without changing the meaning.'},
  {id:'Q07',part:2,type:'combine',connector:'if',skill:'Condition with if',a:'Prince Zak keeps his promise.',b:'He will clean the frog’s pond every week.',answers:["If Prince Zak keeps his promise, he will clean the frog's pond every week.","Prince Zak will clean the frog's pond every week if he keeps his promise."],hint:'Keeping the promise is the condition. Cleaning the pond is what proves that it has been met.',explanation:'Keeping the promise is the condition; cleaning the pond is the result.'},
  {id:'Q08',part:2,type:'combine',connector:'when',skill:'Sequence with when',a:'The train crosses the pond bridge.',b:'The frogs cheer from the lily pads.',answers:['When the train crosses the pond bridge, the frogs cheer from the lily pads.','The frogs cheer from the lily pads when the train crosses the pond bridge.'],hint:'What event makes the frogs begin cheering? Put “when” with that event.',explanation:'The train crossing the bridge is the event that prompts the cheering.'},
  {id:'Q09',part:2,type:'combine',connector:'if',skill:'Condition with if',a:'The hose is long enough.',b:'It can reach the bottom of the hole.',answers:['If the hose is long enough, it can reach the bottom of the hole.','The hose can reach the bottom of the hole if it is long enough.'],hint:'What must be true about the hose before it can reach the bottom?',explanation:'Being long enough is the condition. Reversing the ideas changes the cause-and-result meaning.'},
  {id:'Q10',part:2,type:'combine',connector:'when',skill:'Sequence with when',a:'Prince Zak sees his ball bobbing towards the light.',b:'He cries out with delight.',answers:['When Prince Zak sees his ball bobbing towards the light, he cries out with delight.','Prince Zak cries out with delight when he sees his ball bobbing towards the light.'],hint:'Which event causes Prince Zak’s delighted reaction? Think about what he sees first.',explanation:'Seeing the ball come up happens first and causes his delighted reaction.'},
  {id:'Q11',part:3,type:'complete',connector:'if',skill:'Complete an if sentence',stem:'If you complete your homework early,',prompt:'play computer games',answers:['If you complete your homework early, you may play computer games.','If you complete your homework early, you can play computer games.'],hint:'The homework condition comes first. After the comma, write who may do the activity and use the base verb “play”.',explanation:'The result needs a subject (“you”), a suitable modal (“may” or “can”), and the base verb “play”.'},
  {id:'Q12',part:3,type:'complete',connector:'if',skill:'Complete an if sentence',stem:'If the weather is fine,',prompt:'go to the beach',answers:['If the weather is fine, we will go to the beach.','If the weather is fine, we can go to the beach.','If the weather is fine, we may go to the beach.'],hint:'Fine weather is the condition. After the comma, add “we”, a suitable modal, and the complete phrase in brackets.',explanation:'The result needs “we”, a suitable modal, and “go to the beach”.'},
  {id:'Q13',part:3,type:'complete',connector:'if',skill:'Complete an if sentence',stem:'If I miss the bus,',prompt:'take a taxi',answers:['If I miss the bus, I will take a taxi.','If I miss the bus, I can take a taxi.','If I miss the bus, I may take a taxi.'],hint:'Who misses the bus? Keep the same person in the result clause, then add a modal and “take a taxi”.',explanation:'Because “I” misses the bus, the result must also use “I”, followed by a suitable modal and “take a taxi”.'},
  {id:'Q14',part:3,type:'complete',connector:'if',skill:'Complete an if sentence',stem:'____________________ if you feel sleepy.',prompt:'go to bed',answers:['You should go to bed if you feel sleepy.','You may go to bed if you feel sleepy.'],hint:'The condition is already at the end. Before “if”, write advice for “you” using a modal and the complete phrase in brackets.',explanation:'The main clause needs “you”, a suitable modal, and “go to bed”. There is no comma before a final if-clause.'},
  {id:'Q15',part:3,type:'complete',connector:'if',skill:'Complete an if sentence',stem:'____________________ if you continue to misbehave.',prompt:'punished',answers:['You will be punished if you continue to misbehave.','You may be punished if you continue to misbehave.'],hint:'The condition is at the end. Say what may happen to “you”. Remember that “punished” needs the helping verb “be”.',explanation:'The result needs “you”, a modal, the helping verb “be”, and “punished”. There is no comma before the final if-clause.'}
];

window.RailwayParts = [
  {number:1,name:'Palace Garden Rails',range:'Questions 1–5',focus:'Conditions and signals',theme:'garden'},
  {number:2,name:'Pond Bridge Express',range:'Questions 6–10',focus:'Story events in sequence',theme:'pond'},
  {number:3,name:'Moonlit Mountain Line',range:'Questions 11–15',focus:'Complete each if sentence',theme:'mountain'}
];
